function savestereoeyecal(xdva, ydva, xV, yV, ScreenInfo)
%fprintf('\n%e,%e,%e,%e,\n',xdva,ydva,xV,yV)

sereozero = (ScreenInfo.Xsize/ScreenInfo.PixelsPerDegree)/4; 

p = getpref('MonkeyLogic');
fpath = p.Directories.ExperimentDirectory;
fname = [date '-stereoeyecal.txt'];
stereofilename = [fpath fname];

if exist(stereofilename,'file') == 0
    % open new file
    fid = fopen(stereofilename, 'w');
    % header:
    formatSpec =  '%s\t%s\t%s\t%s\t%s\t%s\t%s\r\n';
    fprintf(fid,formatSpec,...
        'Xml',...
        'Yml',...
        'Xeye',...
        'Yeye',...
        'Xvol',...
        'Yvol',...
        'timestamp');
else
    % append
    fid = fopen(stereofilename, 'a');
end
formatSpec =  '%f\t%f\t%f\t%f\t%f\t%f\t%f\r\n';
fprintf(fid,formatSpec,...
    xdva,...
    ydva,...
    (abs(xdva) - sereozero) * sign(xdva),...
    ydva,...
    xV,...
    yV,...
    now);

fclose(fid);